### ISSUE TITLE
翻译报错

### ISSUE THREAD

**Issue by gcxfd** [zjp-CN/bilingual#24]
![image](https://user-images.githubusercontent.com/69608605/143369804-833a60d0-ab1c-4934-81e8-3052ec8d6829.png)

```

❯ bilingual --api baidu -f zh -t en -m README.md
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/z/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/bilingual-0.1.0/src/config.rs:340:73
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

翻译报错，报错截图如上

文件是 https://raw.githubusercontent.com/rmw-lib/mdbx/999589d0067814ae2961f9ccc90b3da415b4ed0c/README.md

另外

1. 对于代码中的注释能也翻译一下吗？可以简单点，比如代码中以 // 开头的行
1. 能不能支持从环境变量读取api key，这样方便放到github action中（不用公开apikey）
1.  能不能支持从 ~/.config/bilingual.toml 读取全局的配置，这样我不用每个项目放一个配置文件

**Comment by zjp-CN** [comment]
1. 解决了翻译报错

    这个报错是链接文字为空，加上百度翻译没返回空串导致的，见 #26 。目前由 #25 解决，真正要解决得关注 #22 。所以目前你可以更新一下 bilingual（v0.1.1 版本），然后：
    - 让空链接文字有文字： 不要 `![](..)`，而是 `![xx](..)`
    - 或者使用腾讯翻译

2. 现在支持你需要的两种账户信息配置方式，见 #27 
3. 代码中的注释我还得想一想，见 #28
