### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by gcxfd** [zjp-CN/bilingual#30]
我打算把我用vuepress搭建的静态博客用bilingual自动翻译成为各国语言
但是，遇到4个问题

- [ ]  如何只输出译文而不输出原文呢？

- [ ]  如下图`---`，在每个markdown文件开头，vuepress规定了一些网页配置，但是这些配置不能也不需要翻译，能支持不翻译吗？

![image](https://user-images.githubusercontent.com/69608605/143885708-2e1c2766-5fb8-455d-a46a-80c2e11f6cb0.png)

不少静态博客都是这种方式来做一些配置，比如 [docusaurus](https://demopark.github.io/docusaurus-docs-Zh_CN/docs/api-doc-markdown.html)
![image](https://user-images.githubusercontent.com/69608605/143886351-bba20a28-320f-4599-a41e-63602264c571.png)

- [x]  另外，貌似并不会从~/.config/bilingual.toml读取配置。我看代码写的是
`const GLOBAL_BILINGUAL_TOML: &str = "~/.config/bilingual.toml";`
这样应该不行，`~`rust不能识别为home（其实这是shell提供的替换），应该用 https://docs.rs/dirs/4.0.0/dirs/fn.home_dir.html 

- [x]  命令行最好支持-v查看版本

可以参考 Cargo 使用 build.rs 动态生成版本号 https://blog.biofan.org/2019/08/cargo-build-script/

**Comment by gcxfd** [comment]
另外，用腾讯翻译之后，连接都没了

```
底层代码计划 [rust](https://www.rust-lang.org) 编写。

The underlying code is planned to be written by rust.

手机端打算用 [北海 Kraken](https://openkraken.com) 开发。

The mobile phone is going to be developed with Beihai Kraken.

桌面端打算用 [Electron](https://www.electronjs.org) 开发。

The desktop side is going to be developed in Electron.

```

**Comment by zjp-CN** [comment]
> 链接都没了

链接还没改样式。。。
#22

**Comment by gcxfd** [comment]
@zjp-CN 

我看了一下，如果输入加上('1 xx)，输出也会是类似格式，那么可以用这个进行辅助定位，然后再生成链接。

比如下面这样

底层代码计划用 ('1 rust) 编写。

The underlying code is planned to be written in ('1 rust).

**Comment by zjp-CN** [comment]
> 如果输入加上('1 xx)，输出也会是类似格式

没懂诶

**Comment by zjp-CN** [comment]
> 底层代码计划 [rust](https://www.rust-lang.org) 编写。
> 
> The underlying code is planned to be written by rust.

链接样式：
1. 目前以段落为整体提取出文字，所以被翻译文字是：
    > 底层代码计划 rust 编写。

    这可以得到最好的翻译结果。
2. 如果拆分出来，就会分成三段被翻译文字：
    > 底层代码计划
    > rust
    > 编写。

   然后拼接起来：
   > The underlying code plan rust write.
   
   很容易造成翻译不准确。

这个状况是因为：文字应该作为整体来表达（比如以句子、段落、标题作为整体），而样式毫无章法，如果要和原文一样的样式，只能分开翻译。

翻译 MD 和翻译 HTML 会一样遇到问题。

比如用谷歌浏览器和谷歌网页翻译看下面的文字（忽略不准确的翻译结果）：

![image](https://user-images.githubusercontent.com/25300418/143995000-4f3c0815-1c05-4f25-b79e-cae1194913e0.png)

带有样式的句子肯定也是按照样式拆分文字再翻译的：

![image](https://user-images.githubusercontent.com/25300418/143995017-6a9dc118-7aa5-44d0-b14b-108330cbcbd2.png)

**Comment by gcxfd** [comment]
我的意思是，不用拆分为3个句子

原文  ：底层代码计划 [rust](https://www.rust-lang.org) 编写。

变形后给api的文本
底层代码计划 (‘1 rust) 编写。

api翻译后的文本 
The underlying code is planned to be written in ('1 rust).

然后在替换为

The underlying code is planned to be written in [rust](https://www.rust-lang.org) .

**Comment by zjp-CN** [comment]
机器翻译现在没那么智能，如果可以这样标记，还存在我说的样式影响原文的问题吗。。。

你可以自己测试一下：
> 底层代码计划 ('1 rust) 编写。

传给百度翻译：
> The underlying code plan ('1 trust) is written.

**Comment by gcxfd** [comment]
这个与标记无关，百度直接把rust翻译为trust，你不加也一样

底层代码计划 rust编写。
The underlying code is planned to be written by trust.

**Comment by gcxfd** [comment]
> 机器翻译现在没那么智能，如果可以这样标记，还存在我说的样式影响原文的问题吗。。。
> 
> 你可以自己测试一下：
> 
> > 底层代码计划 ('1 rust) 编写。
> 
> `bilingual -a baidu -f zh -t en "底层代码计划 ('1 rust) 编写。"`
> 
> 传给百度翻译：
> 
> > The underlying code plan ('1 trust) is written.
> 
> `bilingual -a tencent -f zh -t en "底层代码计划 ('1 rust) 编写。"`
> 
> 传给腾讯翻译：
> 
> > The underlying code plan ('1 rust) is written.

嗯，我意思就是在程序输输给api，和 api输出到markdown，之间用rust加上的标记转换，这样就可以比较完美的让链接保持可点击。

**Comment by zjp-CN** [comment]
> 之间用rust加上的标记转换

好的，我理解你说的标记是什么意思了。

但是，你忽略了这个事实：

命令行知道 `('1 rust) ` 是一个标记，但是它并不知道标记翻译后对应哪些内容，因为标记压根没有被单独翻译。

**Comment by gcxfd** [comment]
> > 之间用rust加上的标记转换
> 
> 好的，我理解你说的标记是什么意思了。
> 
> 但是，你忽略了这个事实：
> 
> 命令行知道 `('1 rust) ` 是一个标记，但是它并不知道标记翻译后对应哪些内容，因为标记压根没有被单独翻译。

原始输入
```
利用[md-padding](https://github.com/harttle/md-padding)和github commit hook ，[自动给中文和英文之间加上空格](https://github.com/rmw-link/blog-vuepress2/blob/ce966b52f0a06bf2748af36f539f50eadc9eea3c/script/hook.coffee#L46)
```

程序内部转码
```
利用('0 md-padding)('1 自动给中文和英文之间加上空格)
```
同时构建字典 
```
map[0] = https://github.com/harttle/md-padding
map[1]=https://github.com/rmw-link/blog-vuepress2/blob/ce966b52f0a06bf2748af36f539f50eadc9eea3c/script/hook.coffee#L46
```

翻译结果
Using MD padding ('1 automatically adds a space between Chinese and English)

然后，程序抽取 ('\d+ ... )，替换生成链接，输出markdown

**Comment by zjp-CN** [comment]
传给 API 的待翻译文字是？

**Comment by gcxfd** [comment]
> 传给 API 的待翻译文字是？

给命令行的文字是 

```
利用[md-padding](https://github.com/harttle/md-padding)和github commit hook ，[自动给中文和英文之间加上空格](https://github.com/rmw-link/blog-vuepress2/blob/ce966b52f0a06bf2748af36f539f50eadc9eea3c/script/hook.coffee#L46)
```

程序给腾讯api的文字是
```
利用('0 md-padding)('1 自动给中文和英文之间加上空格)
```

**Comment by zjp-CN** [comment]
程序给腾讯api的文字是：
"利用" "md-padding" "和github commit hook" "自动给中文和英文之间加上空格"
```
Use


Md-padding


And github commit hook


Automatically add a space between Chinese and English
```

然后变成这样：

```text
Use [Md-padding](...) And github commit hook [Automatically add a space between Chinese and English](...)
```

是吗？

**Comment by gcxfd** [comment]
用"做标记，如果有多个，没办法确定顺序啊。
另外如下图，貌似腾讯输出不会给引号编程回车
![image](https://user-images.githubusercontent.com/69608605/144000463-4c099383-1e82-4014-b7ad-4ba23122026d.png)

**Comment by zjp-CN** [comment]
你这种做法不就是根据样式拆分句子去翻译吗？

---

BTW

> 程序给腾讯api的文字是：
> "利用" "md-padding" "和github commit hook" "自动给中文和英文之间加上空格"

改成：
> ["利用", "md-padding", "和github commit hook", "自动给中文和英文之间加上空格"]

因为用 JSON 传给 腾讯翻译。

**Comment by gcxfd** [comment]
https://docs.microsoft.com/zh-cn/azure/cognitive-services/translator/document-translation/overview
我发现一个新的解决方案，azure支持翻译markdown
https://github.com/menthays/markdown-translator/blob/master/README.zh.md
我先去试试

**Comment by gcxfd** [comment]
@zjp-CN 
https://github.com/rmw-lib/node/tree/master/markdown-translate
最终，还是我自己写了一个脚本解决了我的所有问题 ^_^
